"""Initial schema

Revision ID: c70ecd2438af
Revises: 
Create Date: 2026-06-10 02:01:55.155244
"""
from alembic import op
import sqlalchemy as sa


revision = 'c70ecd2438af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_configs',
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ai_cache',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('student_verified', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('banned_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('listings',
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('license', sa.String(length=32), nullable=False),
    sa.Column('delivery_method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('demo_url', sa.String(length=512), nullable=True),
    sa.Column('demo_health', sa.String(length=16), nullable=False),
    sa.Column('managed_hosting', sa.String(length=16), nullable=False),
    sa.Column('vitrine_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('badges', sa.JSON(), nullable=False),
    sa.Column('cover', sa.String(length=512), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('rating_distribution', sa.JSON(), nullable=False),
    sa.Column('sdlc', sa.JSON(), nullable=False),
    sa.Column('business_model', sa.JSON(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('ai_draft', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('reporter_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('seller_id', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_seller_id'), ['seller_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('agent', sa.String(length=48), nullable=False),
    sa.Column('listing_id', sa.String(length=32), nullable=True),
    sa.Column('trigger_event', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=48), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_input_hash'), ['input_hash'], unique=False)

    op.create_table('analytic_events',
    sa.Column('listing_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytic_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytic_events_listing_id'), ['listing_id'], unique=False)

    op.create_table('chats',
    sa.Column('buyer_id', sa.String(length=32), nullable=False),
    sa.Column('seller_id', sa.String(length=32), nullable=False),
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('is_agent', sa.Boolean(), nullable=False),
    sa.Column('agent_budget_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('unread_for', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chats_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chats_seller_id'), ['seller_id'], unique=False)

    op.create_table('feature_requests',
    sa.Column('buyer_id', sa.String(length=32), nullable=False),
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_charge_cents', sa.Integer(), nullable=True),
    sa.Column('developer_charge_cents', sa.Integer(), nullable=True),
    sa.Column('developer_approved', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_requests_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_requests_listing_id'), ['listing_id'], unique=False)

    op.create_table('listing_embeddings',
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('listing_fields',
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_fields_listing_id'), ['listing_id'], unique=False)

    op.create_table('listing_media',
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_media_listing_id'), ['listing_id'], unique=False)

    op.create_table('listing_tiers',
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_tiers_listing_id'), ['listing_id'], unique=False)

    op.create_table('reviews',
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_listing_id'), ['listing_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('sender_id', sa.String(length=32), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_agent_rep', sa.Boolean(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_chat_id'), ['chat_id'], unique=False)

    op.create_table('negotiations',
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=True),
    sa.Column('target_cents', sa.Integer(), nullable=True),
    sa.Column('buyer_readme_context', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negotiations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiations_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negotiations_chat_id'), ['chat_id'], unique=False)

    op.create_table('orders',
    sa.Column('buyer_id', sa.String(length=32), nullable=False),
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('seller_id', sa.String(length=32), nullable=False),
    sa.Column('tier_id', sa.String(length=32), nullable=True),
    sa.Column('tier_name', sa.String(length=80), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('commission_cents', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('escrow_status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['listing_tiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('deliveries',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_url', sa.String(length=512), nullable=True),
    sa.Column('license_key', sa.String(length=128), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_order_id'), ['order_id'], unique=False)

    op.create_table('payouts',
    sa.Column('seller_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payout_method', sa.String(length=16), nullable=False),
    sa.Column('payout_details', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_seller_id'), ['seller_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_seller_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_order_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_seller_id'))
        batch_op.drop_index(batch_op.f('ix_orders_listing_id'))
        batch_op.drop_index(batch_op.f('ix_orders_buyer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('negotiations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiations_chat_id'))
        batch_op.drop_index(batch_op.f('ix_negotiations_buyer_id'))

    op.drop_table('negotiations')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_chat_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_listing_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_buyer_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('listing_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_tiers_listing_id'))

    op.drop_table('listing_tiers')
    with op.batch_alter_table('listing_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_media_listing_id'))

    op.drop_table('listing_media')
    with op.batch_alter_table('listing_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_fields_listing_id'))

    op.drop_table('listing_fields')
    op.drop_table('listing_embeddings')
    with op.batch_alter_table('feature_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_requests_listing_id'))
        batch_op.drop_index(batch_op.f('ix_feature_requests_buyer_id'))

    op.drop_table('feature_requests')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_seller_id'))
        batch_op.drop_index(batch_op.f('ix_chats_listing_id'))
        batch_op.drop_index(batch_op.f('ix_chats_buyer_id'))

    op.drop_table('chats')
    with op.batch_alter_table('analytic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytic_events_listing_id'))

    op.drop_table('analytic_events')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_input_hash'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_seller_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))

    op.drop_table('reports')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_slug'))
        batch_op.drop_index(batch_op.f('ix_listings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_listings_category'))

    op.drop_table('listings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('audit_log')
    op.drop_table('ai_cache')
    op.drop_table('admin_configs')
    # ### end Alembic commands ###
